_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  SOURCE_DOMAIN:
    TRAIN: ("cityscapes_train",)
  TARGET_DOMAIN:
    TRAIN: ("foggy-cityscapes_train",)
  TRAIN: ("cityscapes_train",)
  TEST: ("foggy-cityscapes_test",)
MODEL:
  META_ARCHITECTURE: "SAPRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 1
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  KEYPOINT_ON: False
  MASK_ON: False
  DOMAIN_ADAPTATION_ON: True
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    FC_DIM: 256
  DA_HEAD:
    IN_FEATURE: "p6"
    IN_CHANNELS: 256
    NUM_ANCHOR_IN_IMG: 5
    EMBEDDING_KERNEL_SIZE: 3
    EMBEDDING_NORM: True
    EMBEDDING_DROPOUT: True
    FUNC_NAME: "cross_entropy"
    FOCAL_LOSS_GAMMA: 5.0
    POOL_TYPE: 'avg'
    LOSS_WEIGHT: 1.0
    WINDOW_STRIDES: [2, 2, 2, 2, 2]
    WINDOW_SIZES: [3, 6, 9, 12, 14]
  PROPOSAL_GENERATOR:
    NAME: "SAPRPN"
  RESNETS:
    DEPTH: 101
INPUT:
  MIN_SIZE_TRAIN: (864, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
SOLVER:
  IMS_PER_BATCH: 1 # batch size
  STEPS: (96000, 132000)
  BASE_LR: 0.0001
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 5000